name: Create New Release On top
description: Publish a new release of this repo
title: Make a Release
labels:
  - release
body:
  - type: input
    id: blog-title
    attributes:
      label: | 
      Blog Title 1
      Blog Title 2
      description: Set the title of the blog post
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## Prepare a new release
        Use the form below to prepare a new release of this repo.
        Close this issue when the checklist is complete.
  - type: input
    id: manager
    attributes:
      label: Release manager
      description: GitHub handle of who is responsible for this release; assign this issue to this user
      placeholder: "@this-repo-bot"
    validations:
      required: true
  - type: input
    id: smoke-tester
    attributes:
      label: Smoke tester
      description: GitHub handle of who is responsible for smoke testing this release
      placeholder: "@this-repo-bot"
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Release version
      description: Calver-formatted version for this release
      placeholder: YYYY.0M.R
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Release checklist
  - type: checkboxes
    id: release-checklist
    attributes:
      label: Release checklist
      description: Complete these items in sequence as the release progresses
      options:
        - label: Edit the title of this release issue to include the release version
        - label: Create a release candidate tag on `main` and push it
        - label: QA the app in test
        - label: Create a release tag on `main` and push it
        - label: Smoke test the app in prod, leaving a comment on this issue indicating smoke testing results
        - label: Edit release notes with additional context, images, animations, etc. as-needed
        - label: Edit release notes to link to release issue