name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-rc[0-9]+"

permissions:
  contents: write
  packages: write

jobs:
  ci:
    uses: lalver1/gh-release-test/.github/workflows/shared-release.yaml@main

  build:
    needs: ci
    if: ${{ (github.ref_type != 'tag' && github.ref_name || contains(github.ref, 'rc') && 'test' || 'prod') == 'prod'}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Gr1N/setup-poetry@v8
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"
      - name: Setup the project
        run: poetry install
      - name: Build sdist and wheel
        run: poetry build
      - name: Publish the release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.*
