name: release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: poetry build
      - name: Publish the release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/gh_release_test-0.1.0-py3-none-any.whl
            gh_release_test-0.1.0.tar.gz
